name: NewHope512-CCAKEM
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 928
length-secret-key: 1888
length-ciphertext: 1120
length-shared-secret: 32
nistkat-sha256: 4290da64305e70e65766be5d4e488dee2b4b238172876ceefc931934b6964a7d
principal-submitters:
  - Thomas Pöppelmann
auxiliary-submitters:
- Erdem Alkim
- Roberto Avanzi
- Joppe Bos
- Léo Ducas
- Antonio de la Piedra
- Peter Schwabe
- Douglas Stebila
implementations:
- name: clean
  version: https://github.com/newhopecrypto/newhope/commit/3fc68c6090b23c56cc190a78af2f43ee8900e9d0
